name: Deploy to Vercel

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        id: vercel_deploy
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Debug Deployment Output
        run: |
          echo "Debugging Deployment Output..."
          echo "Deployment Output: ${{ steps.vercel_deploy.outputs }}"

      - name: Fetch /api/config
        run: |
          echo "Fetching /api/config..."
          if [ -z "${DEPLOYMENT_URL}" ]; then
            echo "Error: DEPLOYMENT_URL is empty!"
            exit 1
          fi
          RESPONSE=$(curl -s "${DEPLOYMENT_URL}/api/config")
          echo "API Response: $RESPONSE"
          echo "API_RESPONSE=${RESPONSE}" >> $GITHUB_ENV

      - name: Add Deployment Summary
        uses: actions/github-script@v6
        with:
          script: |
            const deploymentUrl = process.env.DEPLOYMENT_URL;
            const apiResponse = process.env.API_RESPONSE;
            const summaryContent = `
            ## Vercel Deployment Summary
            - **Deployment URL:** [Visit Deployment](${deploymentUrl})
            - **API Response from /api/config:** \`${apiResponse}\`
            `;
            core.summary.addRaw(summaryContent).write();
