name: Link Generator

on:
  workflow_dispatch:
    inputs:
      runs:
        description: 'Number of links to generate'
        required: true
        type: string

jobs:
  invoke_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Initialize Loop
        id: initialize
        run: echo "Preparing to invoke deploy workflow ${{ github.event.inputs.runs }} times."

      - name: Trigger
        env:
          RUNS: ${{ inputs.runs }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for (( i=0; i<RUNS; i++ )); do
            gh workflow run --repo "$GITHUB_REPOSITORY" deploy
          done

      - name: Summarize Deployments
        id: summarize
        run: |
          echo "All deployments completed. Here's a summary:"
          for file in output_*.json; do
            echo "$(cat $file)"
          done
