name: Link Generator

on:
  workflow_dispatch:
    inputs:
      runs:
        description: 'Number of links to generate'
        required: true
        type: string

jobs:
  invoke_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Initialize Loop
        id: initialize
        run: echo "Preparing to invoke deploy workflow ${{ github.event.inputs.runs }} times."

      - name: Dynamic Deployment Steps
        id: invoke
        env:
          RUNS: ${{ github.event.inputs.runs }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          for ((i = 1; i <= RUNS; i++)); do
            echo "Running deploy step #$i..."
            OUTPUT=$(gh workflow run deploy.yml \
              --repo "$GITHUB_REPOSITORY" \
              --ref main \
              --json)
            echo "$OUTPUT" > output_$i.json
            DEPLOYMENT_URL=$(echo "$OUTPUT" | jq -r '.runs[0].url')
            echo "Deployment URL for step #$i: $DEPLOYMENT_URL"
            echo "::group::Deployment #$i"
            echo "Triggered deploy with URL: $DEPLOYMENT_URL"
            echo "::endgroup::"
          done

      - name: Summarize Deployments
        id: summarize
        run: |
          echo "All deployments completed. Here's a summary:"
          for file in output_*.json; do
            echo "$(cat $file)"
          done
