name: Link generator

on:
  workflow_dispatch:
    inputs:
      runs:
        description: 'Number of times to invoke the deploy workflow'
        required: true
        default: 3
        type: number

jobs:
  invoke_reusable:
    uses: ./.github/workflows/reusable_deploy.yml
    with:
      runs: ${{ inputs.runs }}
